# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'início.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(532, 642)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 220, 491, 20))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.velocity_profile = QtWidgets.QCheckBox(self.widget)
        self.velocity_profile.setObjectName("velocity_profile")
        self.horizontalLayout.addWidget(self.velocity_profile)
        self.vector_field = QtWidgets.QCheckBox(self.widget)
        self.vector_field.setObjectName("vector_field")
        self.horizontalLayout.addWidget(self.vector_field)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(12, 250, 485, 32))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(208, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.ok_button = QtWidgets.QPushButton(self.widget1)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout_2.addWidget(self.ok_button)
        spacerItem1 = QtWidgets.QSpacerItem(178, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(10, 10, 491, 199))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_reynolds = QtWidgets.QLabel(self.widget2)
        self.label_reynolds.setObjectName("label_reynolds")
        self.verticalLayout.addWidget(self.label_reynolds)
        self.folder_tensores = QtWidgets.QComboBox(self.widget2)
        self.folder_tensores.setObjectName("folder_tensores")
        self.verticalLayout.addWidget(self.folder_tensores)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_lda = QtWidgets.QLabel(self.widget2)
        self.label_lda.setObjectName("label_lda")
        self.verticalLayout_2.addWidget(self.label_lda)
        self.file_lda = QtWidgets.QComboBox(self.widget2)
        self.file_lda.setObjectName("file_lda")
        self.verticalLayout_2.addWidget(self.file_lda)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_pressure_drop = QtWidgets.QLabel(self.widget2)
        self.label_pressure_drop.setObjectName("label_pressure_drop")
        self.verticalLayout_3.addWidget(self.label_pressure_drop)
        self.pressure_drop = QtWidgets.QComboBox(self.widget2)
        self.pressure_drop.setObjectName("pressure_drop")
        self.verticalLayout_3.addWidget(self.pressure_drop)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 532, 22))
        self.menubar.setObjectName("menubar")
        self.menuIn_cio = QtWidgets.QMenu(self.menubar)
        self.menuIn_cio.setObjectName("menuIn_cio")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuIn_cio.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.velocity_profile.setText(_translate("MainWindow", "Show velocity profile plot"))
        self.vector_field.setText(_translate("MainWindow", "Show vector field"))
        self.ok_button.setText(_translate("MainWindow", "OK"))
        self.label_reynolds.setText(_translate("MainWindow", "Select folder to calculate Reynold\'s tensors:"))
        self.label_lda.setText(_translate("MainWindow", "Select file to calculate LDA velocity:"))
        self.label_pressure_drop.setText(_translate("MainWindow", "Select file to calculate pressure drop:"))
        self.menuIn_cio.setTitle(_translate("MainWindow", "Início"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

